before:
  hooks:
    - go mod download

builds:
  - binary: shinnosuke
    main: ./cmd/shinnosuke/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/tonicbupt/shinnosuke/pkg/version.REVISION={{.Commit}}
      - -X github.com/tonicbupt/shinnosuke/pkg/version.VERSION={{.Version}}
      - -X github.com/tonicbupt/shinnosuke/pkg/version.BUILTAT={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
